version: 2.1

jobs:
  test-xcode-10:
    executor: xcode-10
    steps:
      - setup
      - run-tests:
          destination: "platform=iOS Simulator,name=iPad Air 2,OS=12.0"

  test-xcode-9:
    executor: xcode-9
    steps:
      - setup
      - run-tests:
          destination: "platform=iOS Simulator,name=iPad Air 2,OS=10.3.1"

  check-podspec:
    executor: xcode-10
    steps:
      - setup
      - cocoapods-specs
      - run: bundle exec pod lib lint

  deploy-to-cocoapods:
    executor: xcode-10
    steps:
      - setup
      - cocoapods-specs
      - run: bundle exec pod trunk push

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - restore-gems

  restore-gems:
    description: "Restore Ruby Gems"
    steps:
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  cocoapods-specs:
    description: "Fetch CocoaPods Specs"
    steps:
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

  run-tests:
    description: "Runs the tests"
    parameters:
      destination:
        type: string
        default: "platform=iOS Simulator,name=iPad Air 2,OS=12.0"
    steps:
      - run: bundle exec fastlane test
      - run: bundle exec fastlane build_example destination:"<< parameters.destination >>"
      - store_test_results:
          path: output/scan

executors:
  xcode-10:
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.0.0"
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

  xcode-9:
    working_directory: /Users/distiller/project
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - check-podspec:
          filters:
            tags:
              only: /.*/
      - test-xcode-10:
          filters:
            tags:
              only: /.*/
      - test-xcode-9:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-10
            - test-xcode-9
            - check-podspec
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
